version: "3.1"

services:

  clickhouse:
    build: .
    restart: on-failure
    ports:
      - "8443:8443"
      - "9440:9440"
    environment:
      CLICKHOUSE_DB: ${CLICKHOUSE_DB}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    volumes:
      - ./docker/clickhouse-data:/var/lib/clickhouse
      - ./docker/clickhouse-users.xml:/etc/clickhouse-server/users.xml:ro
      - ./docker/clickhouse-config-ssl.xml:/etc/clickhouse-server/config.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
