version: "3.1"

services:

  clickhouse:
    image: clickhouse/clickhouse-server:23.11.2.11-alpine
    restart: on-failure
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_DB: ${CLICKHOUSE_DB:-default}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER:?InvalidClickhouseUser}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD:?InvalidClickhousePassword}
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    volumes:
      - ./clickhouse-data:/var/lib/clickhouse
      - ./docker/clickhouse-users.xml:/etc/clickhouse-server/users.xml:ro
      - ./docker/clickhouse-config.xml:/etc/clickhouse-server/config.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    stop_grace_period: 60s

  grafana:
    image: grafana/grafana-enterprise:10.2.2
    restart: on-failure
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USER:?InvalidGrafanaUser}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD:?InvalidGrafanaPassword}
      GF_INSTALL_PLUGINS: "grafana-clickhouse-datasource"
    volumes:
      - ./grafana-data:/var/lib/grafana
    user: ${GRAFANA_UID:-0}
    depends_on:
      - clickhouse
