version: "3.1"

services:

  clickhouse:
    image: clickhouse/clickhouse-server:23.2.5.46-alpine
    restart: on-failure
    environment:
      CLICKHOUSE_DB: ${CLICKHOUSE_DB}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    volumes:
      - ./docker/clickhouse-data:/var/lib/clickhouse
      - ./docker/clickhouse-users.xml:/etc/clickhouse-server/users.xml:ro
      - ./docker/clickhouse-config.xml:/etc/clickhouse-server/config.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  chproxy:
    image: tacyuuhon/clickhouse-chproxy:1.24.0
    restart: on-failure
    ports:
      - "9090:9090"
    volumes:
      - ./docker/chproxy-certificate:/opt/certificate
      - ./docker/chproxy-config.yml:/opt/config.yml
    depends_on:
      - clickhouse
